package com.antbell.spring.mbg.mapper;

import com.antbell.spring.mbg.model.UmsEmployee;
import com.antbell.spring.mbg.model.UmsEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    int countByExample(UmsEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    int deleteByExample(UmsEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    int insert(UmsEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    int insertSelective(UmsEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    List<UmsEmployee> selectByExample(UmsEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    UmsEmployee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") UmsEmployee record, @Param("example") UmsEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    int updateByExample(@Param("record") UmsEmployee record, @Param("example") UmsEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    int updateByPrimaryKeySelective(UmsEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    int updateByPrimaryKey(UmsEmployee record);
}