package com.antbell.spring.mbg.model;

import java.io.Serializable;

import io.swagger.annotations.ApiModelProperty;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_employee
 *
 * @mbggenerated do_not_delete_during_merge Mon Jan 27 12:33:36 CST 2020
 */
public class UmsEmployee implements Serializable {
    private Long id;

    @ApiModelProperty(value = "姓名")
    private String name;

    @ApiModelProperty(value = "性别")
    private String male;

    @ApiModelProperty(value = "电话")
    private String telephone;

    @ApiModelProperty(value = "年龄")
    private Integer age;

    @ApiModelProperty(value = "地址")
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_employee.id
     *
     * @return the value of ums_employee.id
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_employee.id
     *
     * @param id the value for ums_employee.id
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_employee.name
     *
     * @return the value of ums_employee.name
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_employee.name
     *
     * @param name the value for ums_employee.name
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_employee.male
     *
     * @return the value of ums_employee.male
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public String getMale() {
        return male;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_employee.male
     *
     * @param male the value for ums_employee.male
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public void setMale(String male) {
        this.male = male;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_employee.telephone
     *
     * @return the value of ums_employee.telephone
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_employee.telephone
     *
     * @param telephone the value for ums_employee.telephone
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_employee.age
     *
     * @return the value of ums_employee.age
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_employee.age
     *
     * @param age the value for ums_employee.age
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_employee.address
     *
     * @return the value of ums_employee.address
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_employee.address
     *
     * @param address the value for ums_employee.address
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_employee
     *
     * @mbggenerated Mon Jan 27 12:33:36 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", male=").append(male);
        sb.append(", telephone=").append(telephone);
        sb.append(", age=").append(age);
        sb.append(", address=").append(address);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}